CREATE DATABASE IF NOT EXISTS twitter_clone;
CREATE TABLE usuarios (
	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	usuario VARCHAR(255) UNIQUE NOT NULL,
	senha VARCHAR(255) NOT NULL,
	nome VARCHAR(255) NOT NULL
);
